"""Module 2: describe how liquidity is distributed through the pool.

This module turns the raw daily snapshots from Module 1 into the report-facing
objects requested in the PDF:

- liquidity profile figures for representative dates,
- a daily TVL decomposition,
- ILR(k) concentration measures,
- a daily liquidity HHI series.

The key conceptual step is that initialized ticks are only the *change points* of
the liquidity curve. To study liquidity "at each price level", we first expand
those change points into tick-spacing intervals with constant active liquidity.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from common.constants import FIGURES_DIR, PROCESSED_DATA_DIR, TICK_SPACING
from common.io_utils import ensure_directory, read_parquet, write_parquet
from common.plotting import save_figure, set_project_style
from common.uniswap_math import (
    amounts_for_liquidity,
    raw_amounts_to_decimal,
    tick_interval_prices,
    tick_to_sqrt_price_x96,
)


ILR_BANDWIDTHS = (0.1, 0.5, 1.0, 2.0, 5.0)


@dataclass(frozen=True)
class Module2Paths:
    """All files produced by Module 2."""

    figure_dir: Path
    data_dir: Path

    @property
    def fig_21(self) -> Path:
        return self.figure_dir / "fig_2_1_liquidity_profiles.png"

    @property
    def fig_22(self) -> Path:
        return self.figure_dir / "fig_2_2_tvl_decomposition.png"

    @property
    def fig_23(self) -> Path:
        return self.figure_dir / "fig_2_3_ilr_timeseries.png"

    @property
    def fig_24(self) -> Path:
        return self.figure_dir / "fig_2_4_lhhi_vs_eth_price.png"

    @property
    def tvl_decomposition(self) -> Path:
        return self.data_dir / "tvl_decomposition.parquet"

    @property
    def concentration_metrics(self) -> Path:
        return self.data_dir / "liquidity_concentration_metrics.parquet"


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=PROCESSED_DATA_DIR)
    parser.add_argument("--figure-dir", type=Path, default=FIGURES_DIR)
    return parser.parse_args()


def load_module2_inputs(data_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load the parquet tables generated by Module 1."""

    liquidity_snapshots = read_parquet(data_dir / "liquidity_snapshots.parquet")
    slot0_snapshots = read_parquet(data_dir / "slot0_snapshots.parquet")
    mint_burn_events = read_parquet(data_dir / "mint_burn_events.parquet")

    if "snapshot_timestamp" in liquidity_snapshots.columns:
        liquidity_snapshots["snapshot_timestamp"] = pd.to_datetime(liquidity_snapshots["snapshot_timestamp"], utc=True)
    if "snapshot_timestamp" in slot0_snapshots.columns:
        slot0_snapshots["snapshot_timestamp"] = pd.to_datetime(slot0_snapshots["snapshot_timestamp"], utc=True)
    if "block_timestamp" in mint_burn_events.columns:
        mint_burn_events["block_timestamp"] = pd.to_datetime(mint_burn_events["block_timestamp"], utc=True)
    return liquidity_snapshots, slot0_snapshots, mint_burn_events


def expand_liquidity_profile(snapshot_frame: pd.DataFrame) -> pd.DataFrame:
    """Turn initialized ticks into a piecewise-constant liquidity profile.

    Module 1 stores one row per initialized tick. Between two initialized ticks,
    active liquidity stays constant. This helper expands those change points into
    every tick-spacing interval so Module 2 can reason about liquidity by price
    segment rather than only by event boundary.
    """

    initialized_ticks = snapshot_frame.sort_values("tick").reset_index(drop=True)
    if initialized_ticks.empty:
        return pd.DataFrame(
            columns=[
                "snapshot_block",
                "snapshot_timestamp",
                "tick",
                "active_liquidity",
                "price_lower",
                "price_upper",
            ]
        )

    rows: list[dict[str, object]] = []
    for row_index, tick_row in enumerate(initialized_ticks.itertuples(index=False)):
        tick_start = int(tick_row.tick)
        if row_index + 1 < len(initialized_ticks):
            tick_stop = int(initialized_ticks.iloc[row_index + 1]["tick"])
        else:
            tick_stop = tick_start + TICK_SPACING

        for interval_tick in range(tick_start, tick_stop, TICK_SPACING):
            price_lower, price_upper = tick_interval_prices(interval_tick, interval_tick + TICK_SPACING)
            rows.append(
                {
                    "snapshot_block": int(tick_row.snapshot_block),
                    "snapshot_timestamp": tick_row.snapshot_timestamp,
                    "tick": interval_tick,
                    "active_liquidity": float(tick_row.active_liquidity),
                    "price_lower": float(price_lower),
                    "price_upper": float(price_upper),
                }
            )

    return pd.DataFrame(
        rows,
        columns=[
            "snapshot_block",
            "snapshot_timestamp",
            "tick",
            "active_liquidity",
            "price_lower",
            "price_upper",
        ],
    )


def pick_reference_snapshots(slot0_snapshots: pd.DataFrame) -> dict[str, int]:
    """Pick the three dates used in the liquidity-profile figure.

    We use:
    - the start of the sample,
    - the day with the largest absolute daily log-return,
    - the end of the sample.
    """

    ordered = slot0_snapshots.sort_values("snapshot_timestamp").reset_index(drop=True).copy()
    ordered["log_return"] = np.log(ordered["price_usdc_per_weth"].astype(float) / ordered["price_usdc_per_weth"].shift(1)).fillna(0.0)
    ordered["abs_log_return"] = ordered["log_return"].abs()

    if len(ordered) == 1:
        high_vol_block = int(ordered.iloc[0]["snapshot_block"])
    else:
        high_vol_block = int(ordered.loc[ordered["abs_log_return"].idxmax(), "snapshot_block"])

    return {
        "start": int(ordered.iloc[0]["snapshot_block"]),
        "high_volatility": high_vol_block,
        "end": int(ordered.iloc[-1]["snapshot_block"]),
    }


def build_tvl_decomposition(mint_burn_events: pd.DataFrame, slot0_snapshots: pd.DataFrame) -> pd.DataFrame:
    """Compute daily TVL split into in-range, above-range, and below-range value."""

    events = mint_burn_events.sort_values(["block_number", "log_index"]).reset_index(drop=True)
    snapshots = slot0_snapshots.sort_values("snapshot_block").reset_index(drop=True)
    active_ranges: defaultdict[tuple[int, int], int] = defaultdict(int)
    next_event_index = 0
    decoded_events = events.to_dict("records")
    rows: list[dict[str, object]] = []

    for snapshot in snapshots.itertuples(index=False):
        while next_event_index < len(decoded_events):
            next_event = decoded_events[next_event_index]
            if int(next_event["block_number"]) > int(snapshot.snapshot_block):
                break

            tick_range = (int(next_event["tick_lower"]), int(next_event["tick_upper"]))
            signed_liquidity = int(next_event["liquidity_raw"]) if next_event["event_type"] == "mint" else -int(next_event["liquidity_raw"])
            active_ranges[tick_range] += signed_liquidity
            if active_ranges[tick_range] == 0:
                active_ranges.pop(tick_range, None)
            next_event_index += 1

        in_range_value = 0.0
        above_range_value = 0.0
        below_range_value = 0.0
        current_price = float(snapshot.price_usdc_per_weth)

        for (tick_lower, tick_upper), liquidity_raw in active_ranges.items():
            if liquidity_raw <= 0:
                continue

            price_lower, price_upper = tick_interval_prices(tick_lower, tick_upper)
            amount0_raw, amount1_raw = amounts_for_liquidity(
                sqrt_price_x96=int(snapshot.sqrtPriceX96),
                sqrt_price_a_x96=tick_to_sqrt_price_x96(tick_lower),
                sqrt_price_b_x96=tick_to_sqrt_price_x96(tick_upper),
                liquidity=liquidity_raw,
            )
            amount0_usdc, amount1_weth = raw_amounts_to_decimal(amount0_raw, amount1_raw)
            position_value = float(amount0_usdc + amount1_weth * Decimal(str(snapshot.price_usdc_per_weth)))

            # In the report language:
            # - "below range" means the current price is below the LP range,
            # - "above range" means the current price is above the LP range.
            if current_price < float(price_lower):
                below_range_value += position_value
            elif current_price > float(price_upper):
                above_range_value += position_value
            else:
                in_range_value += position_value

        rows.append(
            {
                "snapshot_block": int(snapshot.snapshot_block),
                "snapshot_timestamp": snapshot.snapshot_timestamp,
                "price_usdc_per_weth": current_price,
                "tvl_in_range": in_range_value,
                "tvl_above_range": above_range_value,
                "tvl_below_range": below_range_value,
                "tvl_total": in_range_value + above_range_value + below_range_value,
            }
        )

    return pd.DataFrame(rows)


def compute_concentration_metrics(liquidity_snapshots: pd.DataFrame, slot0_snapshots: pd.DataFrame) -> pd.DataFrame:
    """Compute liquidity HHI and ILR(k) for every daily snapshot."""

    if liquidity_snapshots.empty:
        return pd.DataFrame(
            columns=[
                "snapshot_block",
                "snapshot_timestamp",
                "price_usdc_per_weth",
                "l_hhi",
                "ilr_0_1pct",
                "ilr_0_5pct",
                "ilr_1_0pct",
                "ilr_2_0pct",
                "ilr_5_0pct",
            ]
        )

    rows: list[dict[str, object]] = []
    price_lookup = slot0_snapshots[["snapshot_block", "price_usdc_per_weth"]]

    for snapshot_block, initialized_ticks in liquidity_snapshots.groupby("snapshot_block"):
        expanded_profile = expand_liquidity_profile(initialized_ticks)
        expanded_profile = expanded_profile.merge(price_lookup, on="snapshot_block", how="left")
        expanded_profile = expanded_profile[expanded_profile["active_liquidity"] > 0].copy()
        if expanded_profile.empty:
            continue

        expanded_profile["price_midpoint"] = (expanded_profile["price_lower"] * expanded_profile["price_upper"]) ** 0.5
        total_liquidity = float(expanded_profile["active_liquidity"].sum())
        current_price = float(expanded_profile["price_usdc_per_weth"].iloc[0])
        liquidity_share = expanded_profile["active_liquidity"] / total_liquidity

        metric_row = {
            "snapshot_block": int(snapshot_block),
            "snapshot_timestamp": expanded_profile["snapshot_timestamp"].iloc[0],
            "price_usdc_per_weth": current_price,
            "l_hhi": float((liquidity_share**2).sum()),
        }

        for bandwidth in ILR_BANDWIDTHS:
            half_band = bandwidth / 100
            lower_bound = current_price * (1 - half_band)
            upper_bound = current_price * (1 + half_band)
            in_band_liquidity = expanded_profile[
                (expanded_profile["price_midpoint"] >= lower_bound)
                & (expanded_profile["price_midpoint"] <= upper_bound)
            ]["active_liquidity"].sum()
            metric_row[f"ilr_{str(bandwidth).replace('.', '_')}pct"] = float(in_band_liquidity / total_liquidity)

        rows.append(metric_row)

    metrics = pd.DataFrame(rows)
    if metrics.empty:
        return pd.DataFrame(
            columns=[
                "snapshot_block",
                "snapshot_timestamp",
                "price_usdc_per_weth",
                "l_hhi",
                "ilr_0_1pct",
                "ilr_0_5pct",
                "ilr_1_0pct",
                "ilr_2_0pct",
                "ilr_5_0pct",
            ]
        )
    return metrics.sort_values("snapshot_timestamp").reset_index(drop=True)


def plot_liquidity_profiles(
    liquidity_snapshots: pd.DataFrame,
    slot0_snapshots: pd.DataFrame,
    snapshot_lookup: dict[str, int],
    path: Path,
) -> None:
    """Plot the liquidity distribution for three representative dates."""

    set_project_style()
    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)
    title_map = {
        "start": "Start of window",
        "high_volatility": "High-volatility day",
        "end": "End of window",
    }

    for axis, label in zip(axes, ["start", "high_volatility", "end"], strict=True):
        snapshot_block = snapshot_lookup[label]
        profile = expand_liquidity_profile(liquidity_snapshots[liquidity_snapshots["snapshot_block"] == snapshot_block]).copy()
        profile["price_midpoint"] = (profile["price_lower"] * profile["price_upper"]) ** 0.5

        axis.bar(
            profile["price_midpoint"],
            profile["active_liquidity"],
            width=profile["price_upper"] - profile["price_lower"],
            alpha=0.65,
        )

        current_price = float(slot0_snapshots.loc[slot0_snapshots["snapshot_block"] == snapshot_block, "price_usdc_per_weth"].iloc[0])
        axis.axvline(current_price, color="crimson", linestyle="--", linewidth=1.5, label="Current price")
        axis.set_title(title_map[label])
        axis.set_xlabel("USDC per WETH")

    axes[0].set_ylabel("Active liquidity")
    axes[-1].legend(loc="upper right")
    save_figure(fig, path)


def plot_tvl_decomposition(tvl_decomposition: pd.DataFrame, path: Path) -> None:
    """Plot the daily TVL decomposition as a stacked area chart."""

    set_project_style()
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.stackplot(
        tvl_decomposition["snapshot_timestamp"],
        tvl_decomposition["tvl_in_range"],
        tvl_decomposition["tvl_above_range"],
        tvl_decomposition["tvl_below_range"],
        labels=["In range", "Above range", "Below range"],
        alpha=0.85,
    )
    ax.set_title("TVL decomposition over time")
    ax.set_xlabel("Snapshot date")
    ax.set_ylabel("USD value")
    ax.legend(loc="upper left")
    save_figure(fig, path)


def plot_ilr_series(metrics: pd.DataFrame, path: Path) -> None:
    """Plot the ILR(k) time series for all requested bandwidths."""

    set_project_style()
    fig, ax = plt.subplots(figsize=(12, 6))
    labels = {
        "ilr_0_1pct": "ILR +/-0.1%",
        "ilr_0_5pct": "ILR +/-0.5%",
        "ilr_1_0pct": "ILR +/-1%",
        "ilr_2_0pct": "ILR +/-2%",
        "ilr_5_0pct": "ILR +/-5%",
    }
    for column, label in labels.items():
        ax.plot(metrics["snapshot_timestamp"], metrics[column], label=label, linewidth=1.6)
    ax.set_title("In-range liquidity ratio across bandwidths")
    ax.set_xlabel("Snapshot date")
    ax.set_ylabel("Liquidity share")
    ax.legend(loc="upper left", ncol=2)
    save_figure(fig, path)


def plot_lhhi_vs_price(metrics: pd.DataFrame, path: Path) -> None:
    """Plot liquidity concentration together with the ETH price level."""

    set_project_style()
    fig, ax1 = plt.subplots(figsize=(12, 6))
    ax2 = ax1.twinx()

    ax1.plot(metrics["snapshot_timestamp"], metrics["l_hhi"], color="navy", linewidth=1.7, label="L-HHI")
    ax2.plot(metrics["snapshot_timestamp"], metrics["price_usdc_per_weth"], color="darkorange", linewidth=1.4, label="ETH price")

    ax1.set_title("Liquidity concentration and ETH price")
    ax1.set_xlabel("Snapshot date")
    ax1.set_ylabel("L-HHI", color="navy")
    ax2.set_ylabel("USDC per WETH", color="darkorange")

    lines = ax1.get_lines() + ax2.get_lines()
    ax1.legend(lines, [line.get_label() for line in lines], loc="upper left")
    save_figure(fig, path)


def run_module_2(data_dir: Path, figure_dir: Path) -> Module2Paths:
    """Execute the full Module 2 workflow."""

    paths = Module2Paths(figure_dir=ensure_directory(figure_dir), data_dir=ensure_directory(data_dir))
    liquidity_snapshots, slot0_snapshots, mint_burn_events = load_module2_inputs(data_dir)

    reference_snapshots = pick_reference_snapshots(slot0_snapshots)
    tvl_decomposition = build_tvl_decomposition(mint_burn_events, slot0_snapshots)
    concentration_metrics = compute_concentration_metrics(liquidity_snapshots, slot0_snapshots)

    write_parquet(tvl_decomposition, paths.tvl_decomposition)
    write_parquet(concentration_metrics, paths.concentration_metrics)
    plot_liquidity_profiles(liquidity_snapshots, slot0_snapshots, reference_snapshots, paths.fig_21)
    plot_tvl_decomposition(tvl_decomposition, paths.fig_22)
    plot_ilr_series(concentration_metrics, paths.fig_23)
    plot_lhhi_vs_price(concentration_metrics, paths.fig_24)
    return paths


def main() -> None:
    """CLI entry point."""

    args = parse_args()
    run_module_2(data_dir=args.data_dir, figure_dir=args.figure_dir)


if __name__ == "__main__":
    main()
